CREATE TABLE towns (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    county_id INTEGER REFERENCES counties(id),
    name TEXT NOT NULL
);

INSERT INTO towns (county_id, name) VALUES
    (7, 'Andover'),
    (5, 'Ansonia'),
    (8, 'Ashford'),
    (2, 'Avon'),
    (3, 'Barkhamsted'),
    (5, 'Beacon Falls'),
    (2, 'Berlin'),
    (5, 'Bethany'),
    (1, 'Bethel'),
    (3, 'Bethlehem'),
    (2, 'Bloomfield'),
    (2, 'Bolton'),
    (6, 'Bozrah'),
    (5, 'Branford'),
    (1, 'Bridgeport'),
    (3, 'Bridgewater'),
    (2, 'Bristol'),
    (1, 'Brookfield'),
    (8, 'Brooklyn'),
    (3, 'Burlington'),
    (3, 'Canaan'),
    (8, 'Canterbury'),
    (3, 'Canton'),
    (7, 'Chaplin'),
    (5, 'Cheshire'),
    (4, 'Chester'),
    (5, 'Clinton'),
    (6, 'Colchester'),
    (3, 'Colebrook'),
    (2, 'Columbia'),
    (3, 'Cornwall'),
    (2, 'Coventry'),
    (4, 'Cromwell'),
    (1, 'Danbury'),
    (1, 'Darien'),
    (4, 'Deep River'),
    (5, 'Derby'),
    (4, 'Durham'),
    (2, 'East Granby'),
    (4, 'East Haddam'),
    (4, 'East Hampton'),
    (2, 'East Hartford'),
    (5, 'East Haven'),
    (6, 'East Lyme'),
    (2, 'East Windsor'),
    (1, 'Easton'),
    (7, 'Ellington'),
    (2, 'Enfield'),
    (4, 'Essex'),
    (1, 'Fairfield'),
    (2, 'Farmington'),
    (6, 'Franklin'),
    (2, 'Glastonbury'),
    (3, 'Goshen'),
    (2, 'Granby'),
    (1, 'Greenwich'),
    (6, 'Griswold'),
    (6, 'Groton'),
    (5, 'Guilford'),
    (4, 'Haddam'),
    (5, 'Hamden'),
    (8, 'Hampton'),
    (2, 'Hartford'),
    (3, 'Hartland'),
    (3, 'Harwinton'),
    (2, 'Hebron'),
    (3, 'Kent'),
    (8, 'Killingly'),
    (4, 'Killingworth'),
    (6, 'Lebanon'),
    (6, 'Ledyard'),
    (6, 'Lisbon'),
    (3, 'Litchfield'),
    (6, 'Lyme'),
    (5, 'Madison'),
    (2, 'Manchester'),
    (7, 'Mansfield'),
    (4, 'Marlborough'),
    (5, 'Meriden'),
    (3, 'Middlebury'),
    (4, 'Middlefield'),
    (4, 'Middletown'),
    (5, 'Milford'),
    (1, 'Monroe'),
    (6, 'Montville'),
    (3, 'Morris'),
    (5, 'Naugatuck'),
    (2, 'New Britain'),
    (1, 'New Canaan'),
    (1, 'New Fairfield'),
    (3, 'New Hartford'),
    (5, 'New Haven'),
    (6, 'New London'),
    (1, 'New Milford'),
    (2, 'Newington'),
    (1, 'Newtown'),
    (3, 'Norfolk'),
    (5, 'North Branford'),
    (3, 'North Canaan'),
    (5, 'North Haven'),
    (6, 'North Stonington'),
    (1, 'Norwalk'),
    (6, 'Norwich'),
    (6, 'Old Lyme'),
    (4, 'Old Saybrook'),
    (5, 'Orange'),
    (5, 'Oxford'),
    (8, 'Plainfield'),
    (2, 'Plainville'),
    (3, 'Plymouth'),
    (8, 'Pomfret'),
    (4, 'Portland'),
    (6, 'Preston'),
    (5, 'Prospect'),
    (8, 'Putnam'),
    (1, 'Redding'),
    (1, 'Ridgefield'),
    (2, 'Rocky Hill'),
    (3, 'Roxbury'),
    (6, 'Salem'),
    (3, 'Salisbury'),
    (4, 'Saybrook'),
    (8, 'Scotland'),
    (5, 'Seymour'),
    (3, 'Sharon'),
    (1, 'Shelton'),
    (1, 'Sherman'),
    (2, 'Simsbury'),
    (7, 'Somers'),
    (2, 'South Windsor'),
    (3, 'Southbury'),
    (2, 'Southington'),
    (6, 'Sprague'),
    (7, 'Stafford'),
    (1, 'Stamford'),
    (8, 'Sterling'),
    (6, 'Stonington'),
    (1, 'Stratford'),
    (2, 'Suffield'),
    (3, 'Thomaston'),
    (8, 'Thompson'),
    (7, 'Tolland'),
    (3, 'Torrington'),
    (1, 'Trumbull'),
    (7, 'Union'),
    (7, 'Vernon'),
    (8, 'Voluntown'),
    (5, 'Wallingford'),
    (3, 'Warren'),
    (3, 'Washington'),
    (5, 'Waterbury'),
    (6, 'Waterford'),
    (3, 'Watertown'),
    (2, 'West Hartford'),
    (5, 'West Haven'),
    (4, 'Westbrook'),
    (1, 'Weston'),
    (1, 'Westport'),
    (2, 'Wethersfield'),
    (7, 'Willington'),
    (1, 'Wilton'),
    (3, 'Winchester'),
    (8, 'Windham'),
    (2, 'Windsor'),
    (2, 'Windsor Locks'),
    (5, 'Wolcott'),
    (5, 'Woodbridge'),
    (3, 'Woodbury'),
    (8, 'Woodstock');


CREATE INDEX idx_towns_name ON towns(name);

-- Town View
CREATE VIEW towns_view AS
SELECT t.*, c.name AS county
FROM towns t
LEFT JOIN counties c ON c.id = t.county_id;
