CREATE TABLE towns (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    display_name TEXT NOT NULL
);

INSERT INTO towns (name, display_name) VALUES
	('andover', 'Andover'),
	('ansonia', 'Ansonia'),
	('ashford', 'Ashford'),
	('avon', 'Avon'),
	('barkhamsted', 'Barkhamsted'),
	('beacon_falls', 'Beacon Falls'),
	('berlin', 'Berlin'),
	('bethany', 'Bethany'),
	('bethel', 'Bethel'),
	('bethlehem', 'Bethlehem'),
	('bloomfield', 'Bloomfield'),
	('bolton', 'Bolton'),
	('bozrah', 'Bozrah'),
	('branford', 'Branford'),
	('bridgeport', 'Bridgeport'),
	('bridgewater', 'Bridgewater'),
	('bristol', 'Bristol'),
	('brookfield', 'Brookfield'),
	('brooklyn', 'Brooklyn'),
	('burlington', 'Burlington'),
	('canaan', 'Canaan'),
	('canterbury', 'Canterbury'),
	('canton', 'Canton'),
	('chaplin', 'Chaplin'),
	('cheshire', 'Cheshire'),
	('chester', 'Chester'),
	('clinton', 'Clinton'),
	('colchester', 'Colchester'),
	('colebrook', 'Colebrook'),
	('columbia', 'Columbia'),
	('cornwall', 'Cornwall'),
	('coventry', 'Coventry'),
	('cromwell', 'Cromwell'),
	('danbury', 'Danbury'),
	('darien', 'Darien'),
	('deep_river', 'Deep River'),
	('derby', 'Derby'),
	('durham', 'Durham'),
	('east_granby', 'East Granby'),
	('east_haddam', 'East Haddam'),
	('east_hampton', 'East Hampton'),
	('east_hartford', 'East Hartford'),
	('east_haven', 'East Haven'),
	('east_lyme', 'East Lyme'),
	('east_windsor', 'East Windsor'),
	('easton', 'Easton'),
	('ellington', 'Ellington'),
	('enfield', 'Enfield'),
	('essex', 'Essex'),
	('fairfield', 'Fairfield'),
	('farmington', 'Farmington'),
	('franklin', 'Franklin'),
	('glastonbury', 'Glastonbury'),
	('goshen', 'Goshen'),
	('granby', 'Granby'),
	('greenwich', 'Greenwich'),
	('griswold', 'Griswold'),
	('groton', 'Groton'),
	('guilford', 'Guilford'),
	('haddam', 'Haddam'),
	('hamden', 'Hamden'),
	('hampton', 'Hampton'),
	('hartford', 'Hartford'),
	('hartland', 'Hartland'),
	('harwinton', 'Harwinton'),
	('hebron', 'Hebron'),
	('kent', 'Kent'),
	('killingly', 'Killingly'),
	('killingworth', 'Killingworth'),
	('lebanon', 'Lebanon'),
	('ledyard', 'Ledyard'),
	('lisbon', 'Lisbon'),
	('litchfield', 'Litchfield'),
	('lyme', 'Lyme'),
	('madison', 'Madison'),
	('manchester', 'Manchester'),
	('mansfield', 'Mansfield'),
	('marlborough', 'Marlborough'),
	('meriden', 'Meriden'),
	('middlebury', 'Middlebury'),
	('middlefield', 'Middlefield'),
	('middletown', 'Middletown'),
	('milford', 'Milford'),
	('monroe', 'Monroe'),
	('montville', 'Montville'),
	('morris', 'Morris'),
	('naugatuck', 'Naugatuck'),
	('new_britain', 'New Britain'),
	('new_canaan', 'New Canaan'),
	('new_fairfield', 'New Fairfield'),
	('new_hartford', 'New Hartford'),
	('new_haven', 'New Haven'),
	('new_london', 'New London'),
	('new_milford', 'New Milford'),
	('newington', 'Newington'),
	('newtown', 'Newtown'),
	('norfolk', 'Norfolk'),
	('north_branford', 'North Branford'),
	('north_canaan', 'North Canaan'),
	('north_haven', 'North Haven'),
	('north_stonington', 'North Stonington'),
	('norwalk', 'Norwalk'),
	('norwich', 'Norwich'),
	('old_lyme', 'Old Lyme'),
	('old_saybrook', 'Old Saybrook'),
	('orange', 'Orange'),
	('oxford', 'Oxford'),
	('plainfield', 'Plainfield'),
	('plainville', 'Plainville'),
	('plymouth', 'Plymouth'),
	('pomfret', 'Pomfret'),
	('portland', 'Portland'),
	('preston', 'Preston'),
	('prospect', 'Prospect'),
	('putnam', 'Putnam'),
	('redding', 'Redding'),
	('ridgefield', 'Ridgefield'),
	('rocky_hill', 'Rocky Hill'),
	('roxbury', 'Roxbury'),
	('salem', 'Salem'),
	('salisbury', 'Salisbury'),
	('saybrook', 'Saybrook'),
	('scotland', 'Scotland'),
	('seymour', 'Seymour'),
	('sharon', 'Sharon'),
	('shelton', 'Shelton'),
	('sherman', 'Sherman'),
	('simsbury', 'Simsbury'),
	('somers', 'Somers'),
	('south_windsor', 'South Windsor'),
	('southbury', 'Southbury'),
	('southington', 'Southington'),
	('sprague', 'Sprague'),
	('stafford', 'Stafford'),
	('stamford', 'Stamford'),
	('sterling', 'Sterling'),
	('stonington', 'Stonington'),
	('stratford', 'Stratford'),
	('suffield', 'Suffield'),
	('thomaston', 'Thomaston'),
	('thompson', 'Thompson'),
	('tolland', 'Tolland'),
	('torrington', 'Torrington'),
	('trumbull', 'Trumbull'),
	('union', 'Union'),
	('vernon', 'Vernon'),
	('voluntown', 'Voluntown'),
	('wallingford', 'Wallingford'),
	('warren', 'Warren'),
	('washington', 'Washington'),
	('waterbury', 'Waterbury'),
	('waterford', 'Waterford'),
	('watertown', 'Watertown'),
	('west_hartford', 'West Hartford'),
	('west_haven', 'West Haven'),
	('westbrook', 'Westbrook'),
	('weston', 'Weston'),
	('westport', 'Westport'),
	('wethersfield', 'Wethersfield'),
	('willington', 'Willington'),
	('wilton', 'Wilton'),
	('winchester', 'Winchester'),
	('windham', 'Windham'),
	('windsor', 'Windsor'),
	('windsor_locks', 'Windsor Locks'),
	('wolcott', 'Wolcott'),
	('woodbridge', 'Woodbridge'),
	('woodbury', 'Woodbury'),
	('woodstock', 'Woodstock');

CREATE INDEX idx_towns_name ON towns(name);
